#!/usr/bin/with-contenv bash
SNAME="cont-init.d"

log() {
	echo "[$SNAME] $@"
}

PUID=${PUID:-911}
PGID=${PGID:-911}

log "Setting user ID to: $PUID"
usermod -o -u "$PUID" abc > /dev/null 2>&1
log "Setting group ID to: $PGID"
groupmod -o -g "$PGID" abc > /dev/null 2>&1

log "Creating crontab directories"
mkdir -p /config/{15min,hourly,daily,sunday,monday,tuesday,wednesday,thursday,friday,saturday,monthly}

log "Setting directory permissions"
chown -R abc:abc /config

log "Ensuring scripts are executable"
chmod -R +x /config
